New note in spa
ArpitAgrawal001/fullstackopen-submissions pull request #3
Opened 2024-03-13 22:05 UTC by ArpitAgrawal001

Here's a simple flow chart:
```mermaid
sequenceDiagram
    participant Browser
    participant Server
    participant SPA

    Browser->>Server: HTTP request for https://studies.cs.helsinki.fi/exampleapp/spa
    activate Server
    
    Server-->>Browser: SPA files (HTML, CSS, JS) are served
    deactivate Server
    
    Browser->>SPA: Browser receives SPA files
    activate SPA
    
    SPA-->>Browser: SPA initializes and renders
    deactivate SPA
    
    Browser->>Server: AJAX requests for initial data/resources
    activate Server
    
    Server->>SPA: Initial data/resources are served
    deactivate Server
    activate SPA
    
    SPA-->>Browser: User creates a new note
    deactivate SPA
    Note right of SPA: Note creation action triggers an AJAX request
    
    Browser->>Server: AJAX request to create a new note
    activate Server
    
    Server-->>Browser: Confirmation of successful note creation
    deactivate Server
    
    Browser->>SPA: SPA updates interface to display new note
    activate SPA
    
    SPA-->>Browser: Executed the excercise:New note in Single page app diagram
    deactivate SPA
    Note right of Browser: Exercise 0.6
```

2024-03-13 22:06 UTC, ArpitAgrawal001 commented
Sir should i do some modifications in my sequence diagram of Excercise 0.6 or is it ready to merge?

And sir should i delete rest of the feature branches?

2024-03-14 13:34 UTC, mavenik requested changes
@ArpitAgrawal001 I see that your previous exercises are deleted on this branch. Probably because the latest changes in `develop` weren't pulled? I also see that Exercise 0.4 has been deleted for some reason. We need it back.

2024-03-14 13:34 UTC, mavenik commented on Part0/Excercise_0.6.md
> +    Server-->>Browser: Confirmation of successful note creation
This does not talk about the kind of HTTP request (GET/POST) and the status code, response data, etc. Can you update the diagram to include this information?

2024-03-14 18:30 UTC, ArpitAgrawal001 commented on Part0/Excercise_0.6.md
> +    Server-->>Browser: Confirmation of successful note creation
ok sir will update this.

2024-03-14 18:31 UTC, ArpitAgrawal001 commented
> @ArpitAgrawal001 I see that your previous exercises are deleted on this branch. Probably because the latest changes in `develop` weren't pulled? I also see that Exercise 0.4 has been deleted for some reason. We need it back.

Sir but after i will merge this branch in develop , all my three excercises will be available there right?

2024-03-14 18:32 UTC, ArpitAgrawal001 commented
Because in my develop branch excercise 0.4 and excercise 0.5 is available.

And after i merge this branch i have to delete all the 3 feature branches right?

2024-03-15 09:04 UTC, mavenik commented
We need to delete branches, not files. If you delete files, they will be deleted in any branch that you merge your active branch to.

2024-03-15 09:23 UTC, ArpitAgrawal001 commented
Sir so should i have to include excercise 0.4 and excercise 0.5 in my
feature branch?


On Fri, Mar 15, 2024, 14:34 Nikhil Lanjewar ***@***.***>
wrote:

> We need to delete branches, not files. If you delete files, they will be
> deleted in any branch that you merge your active branch to.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ArpitAgrawal001/fullstackopen-submissions/pull/3#issuecomment-1999217254>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDTXPSH7TL7YX5PXHYPLHQLYYK2TLAVCNFSM6AAAAABEU7LKAOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJZGIYTOMRVGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-15 09:23 UTC, ArpitAgrawal001 commented
Along with excercise 0.6

On Fri, Mar 15, 2024, 14:53 Arpit Agrawal ***@***.***> wrote:

> Sir so should i have to include excercise 0.4 and excercise 0.5 in my
> feature branch?
>
>
> On Fri, Mar 15, 2024, 14:34 Nikhil Lanjewar ***@***.***>
> wrote:
>
>> We need to delete branches, not files. If you delete files, they will be
>> deleted in any branch that you merge your active branch to.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ArpitAgrawal001/fullstackopen-submissions/pull/3#issuecomment-1999217254>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BDTXPSH7TL7YX5PXHYPLHQLYYK2TLAVCNFSM6AAAAABEU7LKAOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJZGIYTOMRVGQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-03-18 21:50 UTC, closed without merging